name: "[CI] Continuous Integration"

on:
  pull_request:
    types: [opened, synchronize]

jobs: 
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: "Debug"
              run: "ls -la"
            - name: "Install Dependencies"
              run: "npm ci"
            - name: "Lint"
              run: "npm run lint"
    cypress:
        runs-on: ubuntu-latest
        container: cypress/browsers:node18.12.0-chrome107
        steps:        
        - uses: actions/checkout@v3
        - name: "Install Dependencies"
          run: "npm ci"
        - name: "Test - Cypress"
          run: "npm run test"
